import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./_lib/footer";
import Navbar from "./_lib/navbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body >
      
        <div className="min-h-screen flex flex-col justify-between bg-gradient-to-r from-orange-100 via-orange-100 to-orange-200">
        <Navbar />
            <div className="py-[80px] ">
            {children}
            </div>
          <Footer />
        </div>
      </body>
      
    </html>
  );
}
